sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: 1006273998372-i8khfgn2oi2626i3jsnsen4dhv8v5r3t.apps.googleusercontent.com
      secret: riMzLiD2fb7UOZVrgmaX-Nud
    callback:
      url: http://localhost:8080/auth/google/callback
    token:
      url: https://oauth2.googleapis.com/token
  kakao:
    url: https://kauth.kakao.com/oauth/authorize
    client:
      id: d91182674422a63e8a17b6187a4a7684
      secret: QAtjeRymNHI8TIAEIN0MwZGTTaO2ENi8
    callback:
      url: http://localhost:8080/auth/kakao/callback
    token:
      url: https://kauth.kakao.com/oauth/token
  naver:
    url: https://nid.naver.com/oauth2.0/authorize
    client:
      id: EMzJlqm5ZmbBIJNkrA8_
      secret: huJCAysLGg
    callback:
      url: http://localhost:8080/auth/naver/callback
    token:
      url: https://nid.naver.com/oauth2.0/token
